CREATE TABLE "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_users_by_email" ON "users" ("email");
-- #[toasty::breakpoint]
CREATE TABLE "sessions" (
    "token" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    PRIMARY KEY ("token")
);
-- #[toasty::breakpoint]
CREATE TABLE "decks" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "commander" TEXT NOT NULL,
    "cards" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE INDEX "index_decks_by_user_id" ON "decks" ("user_id");
-- #[toasty::breakpoint]
-- Deck-builder search projection (not a Toasty model; data refreshed on boot).
CREATE TABLE "catalog_cards" (
    "name" TEXT NOT NULL,
    "search_blob" TEXT NOT NULL,
    "card_json" TEXT NOT NULL,
    PRIMARY KEY ("name")
);
