#!/usr/bin/env node
// Regenerate Tailwind @theme CSS + canvas TS from repo-root design.tokens.json (DTCG).
// Usage:
//   node scripts/gen-tokens.mjs          # write
//   node scripts/gen-tokens.mjs --check  # fail if stale
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import StyleDictionary from "style-dictionary";

const here = dirname(fileURLToPath(import.meta.url));
const clientRoot = join(here, "..");
const repoRoot = join(clientRoot, "..");
const tokensPath = join(repoRoot, "design.tokens.json");
const cssOut = join(clientRoot, "styles/tokens.generated.css");
const tsOut = join(clientRoot, "lib/design-tokens.generated.ts");

function kebabToCamel(kebab) {
  return kebab.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function cssVarName(path) {
  // ["text","title","font-weight"] → --text-title--font-weight
  // ["color","forest-floor"] → --color-forest-floor
  // ["drop-shadow","drag"] → --drop-shadow-drag
  if (path.length >= 3 && (path[2] === "font-weight" || path[2] === "line-height")) {
    return `--${path[0]}-${path[1]}--${path[2]}`;
  }
  return `--${path.join("-")}`;
}

function collectDtcgTokens(node, path = []) {
  if (!node || typeof node !== "object" || Array.isArray(node)) {
    return [];
  }

  const tokens = [];
  if (Object.hasOwn(node, "$value")) {
    tokens.push({
      path,
      $type: node.$type,
      $value: node.$value,
    });
  }

  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) {
      continue;
    }
    tokens.push(...collectDtcgTokens(value, [...path, key]));
  }

  return tokens;
}

const sourceTokens = collectDtcgTokens(JSON.parse(readFileSync(tokensPath, "utf8")));

function buildConfig(buildPath) {
  return {
    source: [tokensPath],
    usesDtcg: true,
    hooks: {
      transforms: {
        "name/mtgfr-css": {
          type: "name",
          transform: (token) => cssVarName(token.path),
        },
        "value/css-passthrough": {
          type: "value",
          filter: (token) => (token.$type ?? token.type) === "css",
          transform: (token) => token.$value ?? token.value,
        },
      },
      formats: {
        "mtgfr/tailwind-theme": ({ dictionary }) => {
          const tokens = sourceTokens.length > 0 ? sourceTokens : dictionary.allTokens;
          const lines = tokens.map((t) => {
            const name = cssVarName(t.path);
            const value = t.$value ?? t.value;
            return `  ${name}: ${value};`;
          });
          return (
            `/* GENERATED by client/scripts/gen-tokens.mjs — do not edit.\n` +
            ` * Source: design.tokens.json. Regenerate: bun run gen:tokens\n */\n` +
            `@theme {\n${lines.join("\n")}\n}\n`
          );
        },
        "mtgfr/ts-colors": ({ dictionary }) => {
          const tokens = sourceTokens.length > 0 ? sourceTokens : dictionary.allTokens;
          const colorTokens = tokens.filter((t) => t.path[0] === "color");
          const entries = colorTokens.map((t) => {
            const key = kebabToCamel(t.path.slice(1).join("-"));
            const value = t.$value ?? t.value;
            return `  ${key}: ${JSON.stringify(value)},`;
          });
          return (
            `/* GENERATED by client/scripts/gen-tokens.mjs — do not edit.\n` +
            ` * Source: design.tokens.json. Regenerate: bun run gen:tokens\n */\n` +
            `export const colors = {\n${entries.join("\n")}\n} as const;\n` +
            `export type ColorToken = keyof typeof colors;\n`
          );
        },
      },
    },
    platforms: {
      css: {
        transforms: ["name/mtgfr-css", "value/css-passthrough"],
        buildPath: `${buildPath}/`,
        files: [
          {
            destination: "tokens.generated.css",
            format: "mtgfr/tailwind-theme",
            options: { showFileHeader: false },
          },
        ],
      },
      ts: {
        transforms: ["name/mtgfr-css", "value/css-passthrough"],
        buildPath: `${buildPath}/`,
        files: [
          {
            destination: "design-tokens.generated.ts",
            format: "mtgfr/ts-colors",
            filter: (token) => token.path[0] === "color",
            options: { showFileHeader: false },
          },
        ],
      },
    },
  };
}

async function generateTo(dir) {
  mkdirSync(dir, { recursive: true });
  // SD 5.5: prefer constructor+config; if that throws, use `new StyleDictionary()` + `await sd.extend(config)`.
  const sd = new StyleDictionary(buildConfig(dir));
  await sd.buildAllPlatforms();
  return {
    css: readFileSync(join(dir, "tokens.generated.css"), "utf8"),
    ts: readFileSync(join(dir, "design-tokens.generated.ts"), "utf8"),
  };
}

const check = process.argv.includes("--check");
const tmp = mkdtempSync(join(tmpdir(), "mtgfr-tokens-"));
try {
  const out = await generateTo(tmp);
  if (check) {
    const curCss = readFileSync(cssOut, "utf8");
    const curTs = readFileSync(tsOut, "utf8");
    if (curCss !== out.css || curTs !== out.ts) {
      console.error("design tokens outputs are stale — run: cd client && bun run gen:tokens");
      process.exit(1);
    }
    console.log("design tokens outputs up to date");
  } else {
    mkdirSync(dirname(cssOut), { recursive: true });
    mkdirSync(dirname(tsOut), { recursive: true });
    writeFileSync(cssOut, out.css);
    writeFileSync(tsOut, out.ts);
    console.log(`wrote ${cssOut}\nwrote ${tsOut}`);
  }
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
