#!/usr/bin/env python3
"""Generate docs/CR_INDEX.md from CR citations in crates/engine (src + tests).

Run via: just engine-cr-index
Check freshness: just engine-cr-index-check
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

try:
    import fcntl
except ImportError:  # Windows
    fcntl = None  # type: ignore[assignment]

ROOT = Path(__file__).resolve().parents[1]
ENGINE = ROOT / "crates" / "engine"
OUT = ROOT / "docs" / "CR_INDEX.md"

# Matches in-tree spelling: "CR 601.2c", "CR 704", "CR 603.6c/603.10"
CR_TOKEN = re.compile(r"CR\s+([0-9]+(?:\.[0-9a-z]+)*)", re.IGNORECASE)
# Optional inclusive integer range after a bare chapter number: "CR 506–511" / "CR 506-511"
CR_RANGE = re.compile(
    r"CR\s+(\d+)\s*[\u2013\-]\s*(\d+)\b",
    re.IGNORECASE,
)
# Full secondary ids: "CR 603.6c/603.10" or "CR 603.6c/603.10.1"
SLASH_FULL = re.compile(r"/([0-9]+(?:\.[0-9a-z]+)*)")
# Letter-only siblings sharing the stem: "CR 704.5m/n", "CR 704.5a/c/g", "CR 103.8a/c"
SLASH_LETTER = re.compile(r"/([a-z]+)")

SNIPPET_MAX = 100


def rule_sort_key(rule: str) -> tuple:
    """Numeric-aware: 601.2 < 601.2c < 602."""
    parts: list[tuple[int, str]] = []
    for segment in rule.split("."):
        m = re.match(r"^(\d+)(.*)$", segment)
        if m:
            parts.append((int(m.group(1)), m.group(2)))
        else:
            parts.append((0, segment))
    return tuple(parts)


def letter_stem(rule: str) -> str:
    """Strip a trailing letter run so `704.5m` / `n` → stem `704.5`."""
    return re.sub(r"[a-z]+$", "", rule)


def extract_rules(line: str) -> list[str]:
    rules: list[str] = []
    # Expand chapter ranges first (CR 506–511 → 506..511)
    for m in CR_RANGE.finditer(line):
        lo, hi = int(m.group(1)), int(m.group(2))
        if lo > hi or hi - lo > 50:
            continue
        rules.extend(str(n) for n in range(lo, hi + 1))
    for m in CR_TOKEN.finditer(line):
        first = m.group(1)
        # Skip the lower bound of a range already expanded (matched as bare "506" of "506–511")
        if m.end() < len(line) and line[m.end() :].lstrip().startswith(("\u2013", "-")):
            continue
        rules.append(first)
        stem = letter_stem(first)
        rest = line[m.end() :]
        pos = 0
        while pos < len(rest) and rest[pos] == "/":
            full = SLASH_FULL.match(rest, pos)
            if full:
                rules.append(full.group(1))
                pos = full.end()
                continue
            letter = SLASH_LETTER.match(rest, pos)
            if letter:
                rules.append(stem + letter.group(1))
                pos = letter.end()
                continue
            break
    return rules


def snippet(line: str) -> str:
    text = line.strip()
    for prefix in ("//!", "///", "//", "#"):
        if text.startswith(prefix):
            text = text[len(prefix) :].strip()
            break
    text = re.sub(r"\s+", " ", text)
    if len(text) > SNIPPET_MAX:
        text = text[: SNIPPET_MAX - 1] + "…"
    return text


def collect() -> dict[str, list[tuple[str, int, str]]]:
    hits: dict[str, list[tuple[str, int, str]]] = defaultdict(list)
    roots = [ENGINE / "src", ENGINE / "tests"]
    for base in roots:
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.rs")):
            rel = path.relative_to(ROOT).as_posix()
            try:
                lines = path.read_text(encoding="utf-8").splitlines()
            except OSError as e:
                print(f"warning: skip {rel}: {e}", file=sys.stderr)
                continue
            for i, line in enumerate(lines, start=1):
                if "CR " not in line and "CR\t" not in line:
                    continue
                for rule in extract_rules(line):
                    hits[rule].append((rel, i, snippet(line)))
    return hits


def render(hits: dict[str, list[tuple[str, int, str]]]) -> str:
    rules = sorted(hits.keys(), key=rule_sort_key)
    # Deduped rule→line edges and unique source lines (one physical cite may map to many rules)
    edge_count = 0
    unique_lines: set[tuple[str, int]] = set()
    deduped: dict[str, list[tuple[str, int, str]]] = {}
    for rule in rules:
        seen: set[tuple[str, int]] = set()
        entries: list[tuple[str, int, str]] = []
        for path, lineno, snip in hits[rule]:
            key = (path, lineno)
            if key in seen:
                continue
            seen.add(key)
            unique_lines.add(key)
            entries.append((path, lineno, snip))
        deduped[rule] = entries
        edge_count += len(entries)

    lines: list[str] = [
        "<!-- Generated by `just engine-cr-index` — do not edit by hand. -->",
        "",
        "# CR → Engine Index",
        "",
        "Reverse index of Comprehensive Rules citations in `crates/engine` (source + tests).",
        "Regenerate with `just engine-cr-index` after adding `CR …` comments.",
        "Check freshness with `just engine-cr-index-check`.",
        "",
        f"**{len(rules)}** unique rules · **{edge_count}** rule→line hits · "
        f"**{len(unique_lines)}** unique source lines",
        "",
        "## Rules",
        "",
    ]
    for rule in rules:
        lines.append(f"### CR {rule}")
        lines.append("")
        for path, lineno, snip in deduped[rule]:
            lines.append(f"- `{path}:{lineno}` — {snip}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def self_test() -> None:
    cases: list[tuple[str, list[str]]] = [
        ("Primary: CR 704 (SBA), CR 603, CR 608", ["704", "603", "608"]),
        ("CR 603.6c/603.10 look-back", ["603.6c", "603.10"]),
        ("CR 603.6c/603.10.1", ["603.6c", "603.10.1"]),
        ("CR 508.1g / CR 802, Ghostly Prison", ["508.1g", "802"]),
        (
            "Primary: CR 506–511 (combat), CR 702",
            ["506", "507", "508", "509", "510", "511", "702"],
        ),
        ("CR 510.2 x the your_tokens", ["510.2"]),
        ("not CR 613 layers", ["613"]),
        ("CR 103.8a/c", ["103.8a", "103.8c"]),
        ("CR 704.5m/n", ["704.5m", "704.5n"]),
        ("CR 704.5a/c/g", ["704.5a", "704.5c", "704.5g"]),
        ("CR 608.2b/c", ["608.2b", "608.2c"]),
        ("CR 702.16b/e", ["702.16b", "702.16e"]),
        ("Primary CR: 704", []),  # colon form is not greppable on purpose
    ]
    for line, expected in cases:
        got = extract_rules(line)
        if got != expected:
            raise AssertionError(f"{line!r}: expected {expected}, got {got}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 0 if docs/CR_INDEX.md matches a fresh generate; else 1",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="run extractor unit checks and exit",
    )
    args = parser.parse_args(argv)

    try:
        self_test()
    except AssertionError as e:
        print(f"self-test failed: {e}", file=sys.stderr)
        return 1
    if args.self_test:
        print("self-test ok")
        return 0

    hits = collect()
    if not hits:
        print("error: no CR citations found", file=sys.stderr)
        return 1
    body = render(hits)

    if args.check:
        if not OUT.is_file():
            print(f"error: missing {OUT.relative_to(ROOT)}; run just engine-cr-index", file=sys.stderr)
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current == body:
            print(f"{OUT.relative_to(ROOT)} is up to date")
            return 0
        print(
            f"error: {OUT.relative_to(ROOT)} is stale; run just engine-cr-index",
            file=sys.stderr,
        )
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    # Exclusive lock + atomic replace so concurrent regenerations never leave a partial file.
    lock_path = OUT.with_suffix(".md.lock")
    tmp = OUT.with_suffix(".md.tmp")
    with open(lock_path, "a+", encoding="utf-8") as lock_file:
        if fcntl is not None:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
        tmp.write_text(body, encoding="utf-8")
        tmp.replace(OUT)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(hits)} unique rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
